### ISSUE TITLE
Investigate SRO-AAE-JBC

### ISSUE THREAD

**Issue by trickeydan** [roboticsoutreach/tasks#19]
This is marked in the inventory as containing Display Pis.

I know that the display pis are in another RUB..

**Comment by kierdavis** [comment]
The inventory record for SRO-AA6-NQ3 also says "display kits" and was modified more recently, so I think you're correct.

The fact that the date and description for SRO-AAE-JBC weren't updated during cupboard packing imply either:

* I missed this RUB when checking everything into the cupboard.
* We've lost this RUB.
