### ISSUE TITLE
Repair broken MBed Bot

### ISSUE THREAD

**Issue by trickeydan** [roboticsoutreach/tasks#2]
At least one of the MBed Bots is broken.

**Comment by jcwilliamson** [comment]
What exactly is wrong with them? I know a at least one has damaged screws holding it together after taking a fall at SOTSEF, and another has a broken header somewhere. These should hopefully both be pretty minor things to fix. This seems like a Monday evening issue for 1-2 people, or perhaps someone taking home the kit and getting it done over a week. I could possibly take a look at this next week after exams.

**Comment by trickeydan** [comment]
> What exactly is wrong with them? I know a at least one has damaged screws holding it together after taking a fall at SOTSEF, and another has a broken header somewhere. 

This is accurate if I remember correctly
