### ISSUE TITLE
Investigate SRO-AAT-OSU

### ISSUE THREAD

**Issue by kierdavis** [roboticsoutreach/tasks#20]
SRO-AAT-OSU is inventoried as containing "USB hubs and pi cables", but I'm 99% sure all the USB hubs and pi cables were packed into the two RUBs currently inventoried as containing kit: SRO-AAM-TI5 and SRO-AAQ-YJN

**Comment by tpoomlmly** [comment]
SRO-AAT-OSU is a motor assembly on one of the RUB-bots
