### ISSUE TITLE
Label Non-Tracked Assets

### ISSUE THREAD

**Issue by trickeydan** [roboticsoutreach/tasks#24]
Some of our assets are non-tracked.

We should label them with paper labels to ensure that the ownership is obvious.

**Comment by kierdavis** [comment]
Things I can think of right now after a scan through the smallpeice kit list. Not saying we have to do all of them.

* [x] Battery bags (I scrawled "SRO" on these when I removed them from the inventory)
* [ ] Tools (this would stop them getting mingled with L2 Labs' tools)
* [ ] USB sticks
* [ ] Ultrasound modules (if we care that much about them)
* [ ] Pi hats
* [ ] Collapsible RUBs

**Comment by trickeydan** [comment]
> Pi hats

Imo these should have a part number on (at least) the second revision. They are a manufactured asset, so are valuable in that we can't just buy more off the shelf.
