### ISSUE TITLE
Hold an AGM.

### ISSUE THREAD

**Issue by jefftheprogrammer** [roboticsoutreach/tasks#29]
Tommy will need to send out an email for holding the AGM by today.

**Comment by tpoomlmly** [comment]
- [x] Open nominations
- [x]  Open voting August 30, 2021 12:00 AM
    - [x]  Freeze spreadsheet
    - [x]  Send email to announce voting open
- [x]  Send meeting link

**Comment by tpoomlmly** [comment]
- [x] upload the minutes
