### ISSUE TITLE
Find better solution for storing BitBots

### ISSUE THREAD

**Issue by trickeydan** [roboticsoutreach/tasks#3]
@Tyler-Ward suggests mini RUBs

**Comment by tpoomlmly** [comment]
These look like the best-fitting size: https://www.reallyusefulproducts.co.uk/uk/html/onlineshop/rub/b01_75litre.php

2 could maybe fit in here: https://www.reallyusefulproducts.co.uk/uk/html/onlineshop/rub/b03_0litre.php

**Comment by tpoomlmly** [comment]
![6 bitBots in as many RUBs](https://github.com/roboticsoutreach/tasks/assets/5463431/30367cc5-3d3c-4ca6-b4f0-e84503d39ed3)

**Comment by tpoomlmly** [comment]
0.75L RUBs ftw
