### ISSUE TITLE
Design new leaflets

### ISSUE THREAD

**Issue by jefftheprogrammer** [roboticsoutreach/tasks#33]
- Potentially 3 new leaflets with different aspects of the society. 
- The back of the leaflet will have a list of events
- They will be consistent in design
- They should have SRO branding

**Comment by jefftheprogrammer** [comment]
Tbd until next meeting is held #35 and dates are decided on #31 .

**Comment by tpoomlmly** [comment]
> Flyering for your club or society is not permitted. Please do not bring flyers and consider alternative methods to showcase your club or society e.g a scannable QR code

**Comment by tpoomlmly** [comment]
Facebook advert's been done instead
