### ISSUE TITLE
Plan out social media campaign

### ISSUE THREAD

**Issue by jefftheprogrammer** [roboticsoutreach/tasks#36]
May involve facebook marketing money.
Will may need to have access to the bank account before this happens. #30

**Comment by jefftheprogrammer** [comment]
Tbd until next meeting is held #35

**Comment by tpoomlmly** [comment]
There's now a [twitter account](https://twitter.com/robotoutreach)

**Comment by jefftheprogrammer** [comment]
We have decided to post a opening statement, some pictures from previous freshers events and a post containing all of the dates and times for our future freshers events. 

The opening statement has been sent and we will use boosts once we have access to the bank account.

**Comment by tpoomlmly** [comment]
[Instagram](https://www.instagram.com/roboticsoutreach/)
