### ISSUE TITLE
Create a labelling system for the roboticsoutreach/tasks page 

### ISSUE THREAD

**Issue by jefftheprogrammer** [roboticsoutreach/tasks#38]
I would like to add some labels that will suit well for this page. I will also add a quite explanation of these labels in the README.md file.

**Comment by jefftheprogrammer** [comment]
These are the Labels I was thinking for urgency:
ASAP - Must be done in the next 24 hours 
URGENT - Must be done in the next few days
Next Meeting - must be done by next meeting
Low Priority - can be done "soon". 

Special tags for:
SOC CRITICAL - Must be done otherwise the society risks collapsing
AGM - An issue related for an AGM
EGM - An issue related for an EGM
New Meeting - A request for a new meeting
Freshers - An issue related to freshers events
Must be in Soton - You have to be in Southampton to complete this task
Meta - An issue related to the tasks page
SUSU - This issue involves SUSU
Fun - Fun related events
Budget - Budget related things
Web - Issues related to the SRO/Sourcebots webpage 

Role related tasks:
President - Something that has to be done by the president
Treasurer - Something that has to be done by the treasurer
Secretary - Something that has to be done by the secretary

@tpoomlmly Does this look good for you?

**Comment by jefftheprogrammer** [comment]
I have added the Procurement, FROZEN and Inventory tags.

**Comment by tpoomlmly** [comment]
This looks great, I like it

**Comment by tpoomlmly** [comment]
I've added 1 more label + explained the unexplained ones in the readme
