### ISSUE TITLE
Create Knowledge base

### ISSUE THREAD

**Issue by jcwilliamson** [roboticsoutreach/tasks#4]
We should have something that details how to do everything for SRO

**Comment by jcwilliamson** [comment]
This should probably include (but not be limited to) the following:
[ ] Safeguarding
[ ] How to set up and run smaller outreach events for different age groups
[ ] How to run larger events (i.e Smallpeice) and possibly the potential IEEE events
[ ] How to order things
[ ] Information about the kit, how to use it, and how to fix it when it goes wrong.
If anyone can think of anything else useful, feel free to comment

**Comment by kierdavis** [comment]
A couple more ideas:
- How to use the inventory
- How to run a meeting

**Comment by trickeydan** [comment]
KB exists. Issues opened there for the content.
