### ISSUE TITLE
Add Twitter details to our webpages

### ISSUE THREAD

**Issue by tpoomlmly** [roboticsoutreach/tasks#41]
We need to add the twitter link to our existing web presence.

- [x]  Knowledgebase
- [x]  Website
- [x]  SUSU page
   - [x] Update `activities@susu.org` on the AGM results when they come out so we can regain access to the page
      "p.s. Can we have a flagpole at our Bunfight table?"
- [x]  Facebook?

**Comment by jefftheprogrammer** [comment]
I do not have access to the SUSU page anymore. Do you/ @tpoomlmly

**Comment by tpoomlmly** [comment]
I don't anymore either. `sro@soton.ac.uk` has an email from SUSU about the new committee so the next point would be to reply to that and say we're getting an AGM underway

**Comment by jefftheprogrammer** [comment]
I added a twitter link to facebook but it is in the description

**Comment by tpoomlmly** [comment]
Done the susu page
