### ISSUE TITLE
Make the new servo boards

### ISSUE THREAD

**Issue by tpoomlmly** [roboticsoutreach/tasks#42]
- [x]  Resubmit the order
  I think the parts have arrived now and are in the cupboard
- [x]  Manufacture the cases
- [x] Assemble the boards
  This will turn into an activity at some point later

**Comment by jefftheprogrammer** [comment]
How do we manufacture the cases?

**Comment by tpoomlmly** [comment]
- [x] laser cut the acrylic
- [x] slot + screw them together

**Comment by tpoomlmly** [comment]
Done as of Smallpeice 2023 (and the power + motor boards too)
