### ISSUE TITLE
Design and write website

### ISSUE THREAD

**Issue by trickeydan** [roboticsoutreach/tasks#6]

**Comment by jcwilliamson** [comment]
@trickeydan it might be worth linking to, or mentioning by name that markdown to web thing that you were talking to Henry and I last night.

**Comment by trickeydan** [comment]
> @trickeydan it might be worth linking to, or mentioning by name that markdown to web thing that you were talking to Henry and I last night.

Ah that would be `mkdocs`, but I think thats more suitable for #4

**Comment by trickeydan** [comment]
We have a website.
