### ISSUE TITLE
Organise SRO welcome talks

### ISSUE THREAD

**Issue by jefftheprogrammer** [roboticsoutreach/tasks#63]
- [x] Figure out what to mention
- [x] Do the powerpoint. 
- [x] Organise the online bunfight even (based on the welcome talk)

**Comment by tpoomlmly** [comment]
Previously lost slideshow here: https://docs.google.com/presentation/d/1vL4WdGhA_YDJYJ4swLomhJOkEPWXta3-WjDOWGL1DTw/edit?usp=sharing

**Comment by tpoomlmly** [comment]
We should also present this at the 1st Space Cadets session for first-year computer scientists

**Comment by tpoomlmly** [comment]
The last one's on 9.10.21 in B32/3077 from 12-5pm

Short presentation to begin with, then transition to bit:bots and lego mindstorms

## Things we need

- Laptops (Denis cupboard)
- Mindstorms (Denis cupboard + b53 lobby cupboard)
- Outreach box
- Black electrical tape

You can program the mindstorms with [makecode](https://makecode.mindstorms.com) like the microbits

## Challenges

- Follow the line
- Avoid the line
- Move in a square/triangle/circle
- Remote controlled robot

**Comment by tpoomlmly** [comment]
Might as well get the rub bots out too
