### ISSUE TITLE
Buy a circlip tool

### ISSUE THREAD

**Issue by tpoomlmly** [roboticsoutreach/tasks#66]

**Comment by trickeydan** [comment]
Don't we already have loads of these in the robot tools?

**Comment by tpoomlmly** [comment]
Maybe we do, I just couldn't find one and the team tool kits are locked

**Comment by trickeydan** [comment]
> Maybe we do, I just couldn't find one and the team tool kits are locked

Not team kits, there are two sets of robot tools: SRO-AAH-CF3 and SRO-AAJ-NZA, apparently in left side of cupboard

**Comment by tpoomlmly** [comment]
Oh the left cupboard - I'll bear that in mind for next time
