### ISSUE TITLE
Compile list of useful links

### ISSUE THREAD

**Issue by tpoomlmly** [roboticsoutreach/tasks#70]
Links we can make into QR codes people can scan when they go to our bunfight stall

**Comment by jefftheprogrammer** [comment]
Website and SUSU website should be qr codes

**Comment by tpoomlmly** [comment]
- [website](https://roboticsoutreach.org)
- [susu page](https://wwwsusu.org/groupts/student-robotics-southampton)
- [discord](https://discord.gg/ywTpFDuyM8)

were the ones we used
