### ISSUE TITLE
Buy battery voltage testers

### ISSUE THREAD

**Issue by tpoomlmly** [roboticsoutreach/tasks#87]
https://www.flyingtech.co.uk/accessories/1-8s-lipo-battery-tester-low-voltage-alarm?sku=LIPO-ALARM-8SCASE

Saves using the chargers to check the voltage

**Comment by trickeydan** [comment]
Pretty sure we already have some of these with the chargers?

**Comment by tpoomlmly** [comment]
we do, just found them
