### ISSUE TITLE
Open a bank account with Metro

### ISSUE THREAD

**Issue by tpoomlmly** [roboticsoutreach/tasks#93]
Barclays bad in many ways

We need:

- [x] EGM minutes showing:
  - We want to open an account for SRO with Metro
  - Who the committee members are (President/Treasurer/Secretary)
  - Who the signatories will be, and "the signing rules for the account"
  - The signatures of 2+ committee members
- [x] The constitution (and related documents) showing:
  - What we do
  - Who the committee members are
  - What the committee members' roles are

[Source](https://www.metrobankonline.co.uk/business/current-accounts/products/community-current-account/)

They're open 8:30-18:00 Mon-Sat, 11:30-17:00 Sun

We should fund it with the money in the old account, but we don't have to wait to start opening the new one.

**Comment by jefftheprogrammer** [comment]
Do we need to inform SUSU and should we get a bank statement from Barclays?

**Comment by tpoomlmly** [comment]
We can inform SUSU when we're done :)

**Comment by tpoomlmly** [comment]
I've amended a copy of the EGM minutes with the extra detail Metro wanted us to include

**Comment by tpoomlmly** [comment]
## Next steps

- Metro will call us when my credit check has gone through
- [ ] Print the revised EGM minutes
- [x] Print the latest constitution
- [x] @Alexbruvv and @tpoomlmly sign the constitution

**Comment by jefftheprogrammer** [comment]
The consitution signing should be done during next week's meeting.

**Comment by tpoomlmly** [comment]
My credit check has successfully gone through :)

- [x] Go to the bank and finish the account opening process (we still need to bring all the documents)

**Comment by tpoomlmly** [comment]
We went to the bank and finished the account opening process :)
The account will be open some time next week.

p.s. the teller said she hadn't used a memory stick in ages; it could improve robot usability to discuss alternatives to using a USB stick to put code on the robot

**Comment by tpoomlmly** [comment]
The bank account is open and they're sending us the cards + online banking details

Will close when we get the cards

**Comment by tpoomlmly** [comment]
Stefan and I now both have a card
